chore: add react-router

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,8 +1,147 @@
-#!/bin/sh
+#!/bin/bash
+. "$(dirname "$0")/_/husky.sh"
 
-format_files() {
-    echo "Formatting files..."
+# STAGED FILES
+# CHECK GIT STATUS LETTERS https://git-scm.com/docs/git-status
+get_staged_files() {
+    if [ "$1" = "changed" ]; then
+        echo "$(git status -s | grep -E '([M|T|A|C|U])(.)(\s)(.)+' | sed s/^...//)"
+        echo "$(git status -s | grep -E '([R])(.)(\s)(.)+' | sed s/^...// | sed -r 's/^(.)+->[[:space:]]//')"
+    else
+        echo "$(git status -s | grep -E '([M|T|A|C|U|D])(.)(\s)(.)+' | sed s/^...//)"
+        echo "$(git status -s | grep -E '([R])(.)(\s)(.)+' | sed s/^...// | sed -r 's/^(.)+->[[:space:]]//')"
+    fi
+}
+
+get_unstaged_files() {
+    if [ "$1" = "changed" ]; then
+        echo "$(git status -s | grep -E '(.)([M|T|A|C|U])(\s)(.)+' | sed s/^...//)"
+        echo "$(git status -s | grep -E '(.)([R])(\s)(.)+' | sed s/^...// | sed -r 's/^(.)+->[[:space:]]//')"
+    else
+        echo "$(git status -s | grep -E '(.)([M|T|A|C|U|D])(\s)(.)+' | sed s/^...//)"
+        echo "$(git status -s | grep -E '(.)([R])(\s)(.)+' | sed s/^...// | sed -r 's/^(.)+->[[:space:]]//')"
+    fi
+}
+
+# READ ENV FILES
+read_env() {
+    ENV_PATH="$(pwd)/.env"
+
+    if [ -f "$ENV_PATH" ]; then
+        source "$ENV_PATH"
+    else
+        echo "ENV FILE NOT FOUND ($ENV_PATH)"
+    fi
+}
+
+print_green() {
+    echo "\033[0;32m$1\033[0m"
+}
+
+print_blue() {
+    echo "\033[0;34m$1\033[0m"
+}
+
+print_yellow() {
+    echo "\033[1;33m$1\033[0m"
+}
+
+print_grey() {
+    echo "\033[1;30m$1\033[0m"
+}
+
+print_cyan() {
+    echo "\033[1;36m$1\033[0m"
 }
 
 # FORMAT FILES
+format_files() {
+    FILES="$(get_staged_files changed | grep -E '.+\.(ts|tsx|js|jsx|css|json|yml|yaml|md)$' || echo)"
+
+    if [ "$FILES" ]; then
+        print_blue "FORMATTING STAGED FILES"
+        print_grey "$FILES"
+        npm run format -- $(echo $FILES) || exit 1
+
+        # ADD FILES TO STAGE
+        git add $FILES
+        echo
+    fi
+}
+
+# REBUILD GRAPHQL
+rebuild_graphql() {
+    FILES="$(get_staged_files | grep -E '.+\.graphql$' || echo)"
+
+    if [ "$FILES" ]; then
+        print_blue "REBUILDING GRAPHQL"
+        print_grey "$FILES"
+
+        npm run graphql && echo || exit 1
+        UNSTAGED_FILES="$(get_unstaged_files | grep -E 'graphql-(object|type)-generated.ts$' || echo)"
+
+        if [ "$UNSTAGED_FILES" ]; then
+            print_cyan "STAGING GENERATED FILES"
+            print_green "$UNSTAGED_FILES"
+
+            git add $UNSTAGED_FILES
+            echo
+        fi
+    fi
+}
+
+# UPDATE PACKAGE-LOCK
+update_package_lock() {
+    FILE="$(get_staged_files | grep -E 'package(-lock)?.json$' || echo)"
+
+    if [ "$FILE" ]; then
+        print_blue "UPDATING LOCK FILES"
+        print_grey "$FILE"
+
+        # RUN NPM INSTALL DEPENDENCIES
+        npm install --ignore-scripts --package-lock-only && echo || exit 1
+
+        # RUN NPM AUDIT
+        print_blue "RUNNING DEPENDENCY AUDIT"
+        npm audit fix && echo || exit 1
+
+        # GET UNSTAGED LOCK FILES
+        UNSTAGED_FILES="$(get_unstaged_files | grep -E 'package(-lock)?.json$' || echo)"
+
+        if [ "$UNSTAGED_FILES" ]; then
+            print_blue "STAGING UPDATED LOCK FILES"
+            print_grey "$UNSTAGED_FILES"
+
+            git add $UNSTAGED_FILES
+            echo
+        fi
+    fi
+}
+
+# REBUILD CI FILES
+rebuild_ci() {
+    FILES="$(get_staged_files | grep -E '\.circleci\/' || echo)"
+
+    if [ "$FILES" ]; then
+        print_blue "REBUILDING CI FILES"
+        npm run circleci && echo || exit 1
+
+        # GET UPDATED CI FILES
+        UNSTAGED_FILES="$(get_unstaged_files | grep -E '\.circleci\/' || echo)"
+
+        if [ "$UNSTAGED_FILES" ]; then
+            print_cyan "STAGING UPDATED CI FILES"
+            print_green "$UNSTAGED_FILES"
+
+            git add $UNSTAGED_FILES
+            echo
+        fi
+    fi
+}
+
+# EXECUTION
+read_env
+# rebuild_ci
+# rebuild_graphql
 format_files
+update_package_lock
